import type { ConcreteCulturalMotif } from "./types"

export const CULTURE_MOTIF_CARDS: ConcreteCulturalMotif[] = [
  {
    id: "MOTIF_GAME_SHOW_QUEST",
    name: "答题/闯关节目语法",
    source: "p0_motif_library",
    motifType: "quest_show",
    actionLogic: "把日常小问题变成一个有完成区和下一关的任务",
    visualSymbols: ["任务卡", "完成区", "关卡提示", "倒计时牌"],
    motionSymbols: ["递出道具", "放入完成区", "人物停住再继续"],
    audioSymbols: ["提示音", "轻快鼓点", "倒计时滴答"],
    productBridgeOptions: ["ritual_object", "unexpected_tool", "solution_clue"],
    compatibleIntentModes: ["creative_first", "audience_first"],
    compatibleCategories: ["general", "personal_care", "mother_baby", "education", "ai_tools"],
    guardrails: ["不能出现真实节目品牌", "商品必须参与动作链"],
  },
  {
    id: "MOTIF_PUBLIC_MYTH_BREAKTHROUGH",
    name: "公共神话闯关破阵",
    source: "p0_motif_library",
    motifType: "myth_tool",
    actionLogic: "用任务门、云纹、破局道具把商品变成解决关键的一步",
    visualSymbols: ["云路", "山石任务门", "抽象光影道具", "真实商品半露"],
    motionSymbols: ["任务门打开", "云纹冲开", "商品被推入闯关线"],
    audioSymbols: ["鼓点加速", "风声骤停", "短促锣点"],
    productBridgeOptions: ["unexpected_tool", "ritual_object", "solution_clue"],
    compatibleIntentModes: ["creative_first", "pain_first"],
    compatibleCategories: ["general", "food_beverage", "sports_fitness", "personal_care", "ai_tools"],
    guardrails: ["不复制现代影视/游戏造型", "不使用具体角色脸、原台词或原音乐"],
  },
  {
    id: "MOTIF_STRATEGY_TABLE_BREAKTHROUGH",
    name: "谋略沙盘一招破局",
    source: "p0_motif_library",
    motifType: "strategy_table",
    actionLogic: "把混乱选择收束到桌面关键一步，商品像一枚决定走向的棋子",
    visualSymbols: ["沙盘桌", "路线标记", "卷轴边缘", "桌边真实商品"],
    motionSymbols: ["手指停在关键路线", "棋子落桌", "商品推入沙盘边缘"],
    audioSymbols: ["棋子落桌声", "纸张摩擦", "低频停顿"],
    productBridgeOptions: ["solution_clue", "evidence_object", "unexpected_tool"],
    compatibleIntentModes: ["creative_first", "pain_first", "offer_first"],
    compatibleCategories: ["ai_tools", "education", "storage_home", "kitchen_tools", "general"],
    guardrails: ["不要指向具体历史人物造型", "不能把策略感拍成古装广告摆拍"],
  },
  {
    id: "MOTIF_TRIAL_EVIDENCE_TABLE",
    name: "证据审判台",
    source: "p0_motif_library",
    motifType: "trial",
    actionLogic: "把痛点和商品摆成证据，让观众先看见可验证细节再听判断",
    visualSymbols: ["中轴桌面", "证据袋", "局部聚光", "商品处于证据核心"],
    motionSymbols: ["证据被推到中心", "手指点位", "镜头压近包装细节"],
    audioSymbols: ["木质拍案声", "突然静音", "纸张轻响"],
    productBridgeOptions: ["evidence_object", "reveal_anchor", "contrast_object"],
    compatibleIntentModes: ["pain_first", "offer_first"],
    compatibleCategories: ["cleaning", "personal_care", "beauty", "food_beverage", "general"],
    guardrails: ["不伪造检测报告或官方背书", "不使用具体法庭剧名称或案件名"],
  },
  {
    id: "MOTIF_RITUAL_OPENING",
    name: "民俗开门仪式",
    source: "p0_motif_library",
    motifType: "ritual",
    actionLogic: "用红金门口、鼓点和开门动作制造进入感，商品成为开场后第一个被看见的物件",
    visualSymbols: ["红金门口", "门缝光", "仪式桌面", "商品在门后出现"],
    motionSymbols: ["门被推开", "道具冲镜", "商品从门后递出"],
    audioSymbols: ["鼓点", "短促锣点", "开门声"],
    productBridgeOptions: ["ritual_object", "social_signal", "sensory_trigger"],
    compatibleIntentModes: ["creative_first", "audience_first", "offer_first"],
    compatibleCategories: ["food_beverage", "cleaning", "storage_home", "mother_baby", "womenswear"],
    guardrails: ["不绑定具体品牌活动", "节庆感必须服务商品进入动作"],
  },
  {
    id: "MOTIF_RAIN_REVEAL",
    name: "烟雨慢揭示",
    source: "p0_motif_library",
    motifType: "rain_reveal",
    actionLogic: "用雨雾、伞缘和慢揭示制造质感悬念，商品承担答案或质感证据",
    visualSymbols: ["雨雾", "伞缘", "湿润石面", "商品局部从雾气里露出"],
    motionSymbols: ["伞边微转", "雾气散开", "商品缓慢推近"],
    audioSymbols: ["细雨声", "轻微水滴", "答案前静音"],
    productBridgeOptions: ["sensory_trigger", "reveal_anchor", "evidence_object"],
    compatibleIntentModes: ["creative_first", "audience_first", "pain_first"],
    compatibleCategories: ["beauty", "personal_care", "womenswear", "food_beverage", "general"],
    guardrails: ["不复制具体影视桥段", "不要只做背景滤镜，必须让商品参与揭示动作"],
  },
]
