import type {
  AttentionMicroPattern,
  AudienceSituationPattern,
  ConstraintRule,
  EventPrimitive,
  FailureMode,
  ProductBridgeRoleResource,
  ProofVisualizationCard,
  ShotCard,
} from "./types"

export type P0CategoryRule = {
  id: string
  canonicalCategory: string
  inferredSubCategory: string
  aliases: string[]
  visualAnchors: string[]
  packagingSignals: string[]
  usageAnchors: string[]
  typicalUseScenes: string[]
  allowedProductActions: string[]
  forbiddenVisualConfusions: string[]
  claimRiskTags: string[]
  modelRiskTags: string[]
  hookStudioCategory: string
}

export const P0_CATEGORY_RULES: P0CategoryRule[] = [
  {
    id: "p0_oral_care_toothpaste",
    canonicalCategory: "personal_care",
    inferredSubCategory: "oral_care_toothpaste",
    aliases: ["toothpaste", "oral care", "牙膏", "口腔", "刷牙"],
    visualAnchors: ["牙膏软管", "管盖", "挤出的膏体", "牙刷"],
    packagingSignals: ["口腔护理包装", "软管包装", "清洁功效信息"],
    usageAnchors: ["挤牙膏", "刷牙", "浴室镜前停住"],
    typicalUseScenes: ["浴室", "睡前", "亲子刷牙", "出门前"],
    allowedProductActions: ["挤出", "递近", "放在牙刷旁", "和牙刷同框"],
    forbiddenVisualConfusions: ["精华液瓶", "面霜罐", "香水瓶", "普通化妆品瓶"],
    claimRiskTags: ["medical_claim", "absolute_whitening"],
    modelRiskTags: ["product_substitution", "tube_to_bottle_drift"],
    hookStudioCategory: "personal_care",
  },
  {
    id: "p0_cleanser_skincare",
    canonicalCategory: "beauty",
    inferredSubCategory: "cleanser_skincare",
    aliases: ["cleanser", "skincare", "洗面奶", "洁面", "护肤"],
    visualAnchors: ["洁面管/瓶", "泡沫", "掌心涂抹", "洗脸台"],
    packagingSignals: ["护肤品包装", "泵头或软管", "成分/肤感信息"],
    usageAnchors: ["起泡", "冲洗", "镜前观察肤感"],
    typicalUseScenes: ["浴室", "洗手台", "晨间护肤", "睡前清洁"],
    allowedProductActions: ["挤出", "揉搓起泡", "靠近脸部但不夸张涂抹"],
    forbiddenVisualConfusions: ["牙膏", "香水瓶", "食品包装"],
    claimRiskTags: ["skin_medical_claim", "instant_cure_claim"],
    modelRiskTags: ["beauty_packaging_drift"],
    hookStudioCategory: "beauty",
  },
  {
    id: "p0_fragrance",
    canonicalCategory: "beauty",
    inferredSubCategory: "fragrance",
    aliases: ["fragrance", "perfume", "香水", "香氛", "香薰"],
    visualAnchors: ["香水瓶", "喷雾", "闻香反应", "桌面光影"],
    packagingSignals: ["玻璃瓶", "瓶盖", "礼盒"],
    usageAnchors: ["喷洒", "闻到后停住", "靠近衣领/房间入口"],
    typicalUseScenes: ["出门前", "约会前", "卧室", "玄关"],
    allowedProductActions: ["轻喷", "拿起闻", "放在梳妆台"],
    forbiddenVisualConfusions: ["护肤精华", "饮料瓶", "清洁喷雾"],
    claimRiskTags: ["emotion_overclaim"],
    modelRiskTags: ["invisible_smell"],
    hookStudioCategory: "beauty",
  },
  {
    id: "p0_cleaning_products",
    canonicalCategory: "cleaning",
    inferredSubCategory: "cleaning_products",
    aliases: ["cleaning", "cleaning products", "清洁", "去污", "拖把", "清洁剂"],
    visualAnchors: ["污渍", "擦拭轨迹", "清洁工具或瓶身", "地面/台面"],
    packagingSignals: ["清洁品包装", "喷头", "拖布/刷头结构"],
    usageAnchors: ["喷洒", "擦拭", "拖地", "前后对比"],
    typicalUseScenes: ["厨房", "浴室", "客厅地面", "餐桌"],
    allowedProductActions: ["喷到污渍旁", "擦过表面", "拖布贴近污渍"],
    forbiddenVisualConfusions: ["护肤品", "食品包装", "电子设备"],
    claimRiskTags: ["sterilization_claim", "absolute_clean_claim"],
    modelRiskTags: ["magic_cleaning"],
    hookStudioCategory: "cleaning",
  },
  {
    id: "p0_snacks_drinks",
    canonicalCategory: "food_beverage",
    inferredSubCategory: "snacks_drinks",
    aliases: ["snacks", "drinks", "food", "beverage", "零食", "饮料", "小吃"],
    visualAnchors: ["包装袋/瓶罐", "入口前反应", "打开包装", "质地近景"],
    packagingSignals: ["食品包装", "口味信息", "规格/组合"],
    usageAnchors: ["开袋", "倒出", "咬一口", "分享给旁人"],
    typicalUseScenes: ["办公室", "客厅", "露营", "追剧"],
    allowedProductActions: ["打开", "倒出", "递给别人", "摆成份量"],
    forbiddenVisualConfusions: ["药品", "化妆品", "清洁剂"],
    claimRiskTags: ["health_food_claim"],
    modelRiskTags: ["food_texture_drift"],
    hookStudioCategory: "food_beverage",
  },
  {
    id: "p0_cups_bottles",
    canonicalCategory: "kitchen_tools",
    inferredSubCategory: "cups_bottles",
    aliases: ["cup", "bottle", "cups/bottles", "杯子", "水杯", "保温杯"],
    visualAnchors: ["杯身", "杯盖", "单手拿取", "水流/水汽"],
    packagingSignals: ["杯具包装", "容量/保温信息"],
    usageAnchors: ["倒水", "盖上杯盖", "放入包内", "桌面拿起"],
    typicalUseScenes: ["办公室", "通勤", "厨房", "户外"],
    allowedProductActions: ["倒水", "单手开合", "放进包侧袋"],
    forbiddenVisualConfusions: ["化妆瓶", "清洁瓶"],
    claimRiskTags: ["temperature_duration_claim"],
    modelRiskTags: ["scale_misread"],
    hookStudioCategory: "kitchen_tools",
  },
  {
    id: "p0_small_appliances",
    canonicalCategory: "kitchen_tools",
    inferredSubCategory: "small_appliances",
    aliases: ["small appliances", "appliance", "小家电", "厨房电器"],
    visualAnchors: ["小家电机身", "按钮/指示灯", "使用中状态"],
    packagingSignals: ["电器包装", "型号/功能区"],
    usageAnchors: ["按下按钮", "打开盖子", "完成提示"],
    typicalUseScenes: ["厨房", "餐桌", "办公室茶水间"],
    allowedProductActions: ["按键", "开盖", "放入食材/物品", "完成后取出"],
    forbiddenVisualConfusions: ["大型家电", "玩具", "数码配件"],
    claimRiskTags: ["safety_claim", "time_exact_claim"],
    modelRiskTags: ["device_shape_drift"],
    hookStudioCategory: "kitchen_tools",
  },
  {
    id: "p0_storage_home",
    canonicalCategory: "storage_home",
    inferredSubCategory: "storage_home_organization",
    aliases: ["storage", "home organization", "收纳", "家居", "整理"],
    visualAnchors: ["收纳盒/架", "乱到整齐", "柜内空间", "桌面前后"],
    packagingSignals: ["家居用品包装", "尺寸/容量信息"],
    usageAnchors: ["放入", "抽拉", "堆叠", "前后对比"],
    typicalUseScenes: ["衣柜", "厨房柜", "桌面", "玄关"],
    allowedProductActions: ["放入物品", "抽拉展示", "并排对比"],
    forbiddenVisualConfusions: ["清洁剂", "食品"],
    claimRiskTags: ["capacity_overclaim"],
    modelRiskTags: ["unrealistic_space_transform"],
    hookStudioCategory: "storage_home",
  },
  {
    id: "p0_pet_products",
    canonicalCategory: "pet",
    inferredSubCategory: "pet_products",
    aliases: ["pet", "pet products", "猫", "狗", "宠物"],
    visualAnchors: ["宠物用品", "宠物反应", "爪子/毛发", "喂食或梳理动作"],
    packagingSignals: ["宠物用品包装", "适用宠物信息"],
    usageAnchors: ["喂食", "梳毛", "清洁", "玩耍"],
    typicalUseScenes: ["客厅", "宠物角", "门口", "阳台"],
    allowedProductActions: ["递近", "放在宠物旁", "主人手部操作"],
    forbiddenVisualConfusions: ["儿童用品", "普通食品"],
    claimRiskTags: ["pet_health_claim"],
    modelRiskTags: ["animal_behavior_unstable"],
    hookStudioCategory: "pet",
  },
  {
    id: "p0_mother_baby",
    canonicalCategory: "mother_baby",
    inferredSubCategory: "mother_and_baby",
    aliases: ["mother-and-baby", "mother baby", "母婴", "宝宝", "婴儿"],
    visualAnchors: ["母婴用品", "柔和材质", "照护动作", "家长手部"],
    packagingSignals: ["母婴包装", "年龄段/温和信息"],
    usageAnchors: ["整理", "递给宝宝", "照护前后"],
    typicalUseScenes: ["卧室", "儿童房", "出门包", "餐椅旁"],
    allowedProductActions: ["轻拿", "整理", "放入妈妈包"],
    forbiddenVisualConfusions: ["医疗用品", "成人护肤"],
    claimRiskTags: ["infant_medical_claim", "safety_absolute_claim"],
    modelRiskTags: ["baby_scene_sensitivity"],
    hookStudioCategory: "mother_baby",
  },
  {
    id: "p0_fashion_shoes_bags",
    canonicalCategory: "womenswear",
    inferredSubCategory: "fashion_shoes_bags",
    aliases: ["fashion", "shoes", "bags", "服饰", "鞋", "包", "穿搭"],
    visualAnchors: ["穿搭主体", "材质纹理", "上身/上脚", "包型"],
    packagingSignals: ["服饰吊牌/鞋盒/包袋包装"],
    usageAnchors: ["换装", "出门前选择", "镜前对比", "单品上身"],
    typicalUseScenes: ["镜前", "通勤", "约会前", "衣柜"],
    allowedProductActions: ["穿上", "背起", "对镜整理", "材质近景"],
    forbiddenVisualConfusions: ["普通布料堆", "不相关饰品"],
    claimRiskTags: ["body_shape_claim"],
    modelRiskTags: ["fit_and_body_drift"],
    hookStudioCategory: "womenswear",
  },
  {
    id: "p0_digital_accessories",
    canonicalCategory: "ai_tools",
    inferredSubCategory: "digital_accessories",
    aliases: ["digital accessories", "digital", "phone accessory", "数码", "手机配件", "电子配件"],
    visualAnchors: ["手机/设备配件", "接口/磁吸/支架", "桌面设备"],
    packagingSignals: ["数码配件包装", "适配型号信息"],
    usageAnchors: ["连接", "吸附", "支起设备", "收纳线材"],
    typicalUseScenes: ["办公桌", "通勤包", "车内", "床头"],
    allowedProductActions: ["连接设备", "单手吸附", "收纳/支撑"],
    forbiddenVisualConfusions: ["大型电器", "玩具"],
    claimRiskTags: ["compatibility_claim"],
    modelRiskTags: ["device_brand_logo_risk"],
    hookStudioCategory: "ai_tools",
  },
  {
    id: "p0_hardware_faucet_extender",
    canonicalCategory: "hardware_faucet_extender",
    inferredSubCategory: "faucet_extender_rotating_joint",
    aliases: ["faucet extender", "rotatable faucet", "1080", "水龙头", "可旋转水龙头", "万向接头", "延伸器", "起泡器", "出水口"],
    visualAnchors: ["水龙头延伸器", "万向接头", "圆柱螺纹接口", "银色金属弯管", "出水口", "旋转接头"],
    packagingSignals: ["水龙头配件图", "1080°标识", "安装配件", "密封圈"],
    usageAnchors: ["安装到现有水龙头", "手部旋转接头", "调整出水方向", "水槽边冲洗"],
    typicalUseScenes: ["厨房水槽", "浴室洗手台", "洗脸台", "家用水池"],
    allowedProductActions: ["旋转接头", "调整出水方向", "打开水流", "手扶接口演示"],
    forbiddenVisualConfusions: ["整套新水龙头", "软管花洒", "可拉伸管", "普通水杯", "金属挂钩"],
    claimRiskTags: ["installation_compatibility_claim", "unverified_angle_claim"],
    modelRiskTags: ["shape_critical_product", "metal_part_morph", "faucet_to_full_fixture_drift"],
    hookStudioCategory: "kitchen_tools",
  },
  {
    id: "p0_general_ecommerce",
    canonicalCategory: "general",
    inferredSubCategory: "general_ecommerce_product",
    aliases: ["general", "unknown", "其他"],
    visualAnchors: ["商品主体", "包装或外形", "使用动作"],
    packagingSignals: ["商品包装", "可见外形锚点"],
    usageAnchors: ["拿起", "放下", "递给别人", "靠近问题现场"],
    typicalUseScenes: ["桌面", "家中", "办公室"],
    allowedProductActions: ["手持", "递出", "放入场景", "执行一个小动作"],
    forbiddenVisualConfusions: ["替换成其它品类", "丢失包装形态"],
    claimRiskTags: ["unsupported_claim"],
    modelRiskTags: ["generic_product_drift"],
    hookStudioCategory: "personal_care",
  },
]

export const AUDIENCE_SITUATION_PATTERNS: AudienceSituationPattern[] = [
  {
    id: "aud_parent_bedtime_routine",
    name: "家长睡前流程卡住",
    lifeState: "睡前最后几分钟，家长想快点完成照护流程",
    emotionalTriggers: ["催促无效", "孩子抗拒", "时间变晚"],
    hiddenDoubts: ["会不会刺激", "孩子愿不愿意配合"],
    likelyScrollReasons: ["场景太熟悉", "孩子反应真实"],
    recognitionSignals: ["牙刷递出又缩回", "灯关一半", "家长停住"],
    commonScenes: ["浴室", "儿童房", "床边"],
    compatibleIntentTypes: ["audience_first", "pain_first", "creative_first"],
    compatibleCategories: ["personal_care", "mother_baby"],
    compatibleHookTypes: ["H2", "H3", "H4", "H7"],
    compatibleEventKinds: ["threshold_event", "handoff_refusal", "daily_action_failure"],
    exampleAudienceInputs: ["3-6 岁孩子家长", "孩子不爱刷牙"],
  },
  {
    id: "aud_commuter_last_second",
    name: "出门前最后一秒",
    lifeState: "马上出门、上镜或见人前发现小问题",
    emotionalTriggers: ["来不及", "怕尴尬", "临门一脚"],
    hiddenDoubts: ["能不能快速解决", "会不会麻烦"],
    likelyScrollReasons: ["门口停住", "镜前反应"],
    recognitionSignals: ["包刚合上又打开", "门口停住", "镜前检查"],
    commonScenes: ["玄关", "电梯口", "办公室门口"],
    compatibleIntentTypes: ["audience_first", "pain_first"],
    compatibleCategories: ["beauty", "womenswear", "digital_accessories", "personal_care"],
    compatibleHookTypes: ["H2", "H3", "H4", "H6"],
    compatibleEventKinds: ["threshold_event", "scene_mismatch"],
    exampleAudienceInputs: ["通勤人群", "上镜前发现小问题"],
  },
  {
    id: "aud_home_cleanup_friction",
    name: "家务清洁挫败",
    lifeState: "重复处理一个家务问题但看不到变化",
    emotionalTriggers: ["反复失败", "手已经累了", "客人快到了"],
    hiddenDoubts: ["是不是真的有用", "会不会更麻烦"],
    likelyScrollReasons: ["污渍/凌乱可见", "旧方法失败"],
    recognitionSignals: ["第三次擦拭", "同一块污渍", "桌面乱到停住"],
    commonScenes: ["厨房", "浴室", "客厅", "柜子前"],
    compatibleIntentTypes: ["pain_first", "offer_first"],
    compatibleCategories: ["cleaning", "storage_home", "kitchen_tools"],
    compatibleHookTypes: ["H1", "H2", "H5"],
    compatibleEventKinds: ["repeated_failure", "object_transformation", "comparison_split"],
    exampleAudienceInputs: ["地面总拖不干净", "桌面总是乱"],
  },
  {
    id: "aud_friend_social_proof",
    name: "朋友/家人先停住",
    lifeState: "旁人反应比主角说明更快",
    emotionalTriggers: ["被抢先试", "被质疑后反转", "旁人围观"],
    hiddenDoubts: ["是不是只有广告会这么说", "别人会不会认可"],
    likelyScrollReasons: ["别人突然看过来", "商品被拿走"],
    recognitionSignals: ["朋友伸手拿走", "家人质疑", "评论式挑战"],
    commonScenes: ["客厅", "办公室", "餐桌"],
    compatibleIntentTypes: ["audience_first", "offer_first"],
    compatibleCategories: ["food_beverage", "beauty", "pet", "womenswear"],
    compatibleHookTypes: ["H3", "H5", "H6"],
    compatibleEventKinds: ["handoff_refusal", "group_reaction", "value_visualization"],
    exampleAudienceInputs: ["朋友看到也想试", "家庭用户"],
  },
  {
    id: "aud_creative_mismatch_viewer",
    name: "普通问题被拍成不普通场景",
    lifeState: "日常小问题突然进入类型片/闯关/仪式语法",
    emotionalTriggers: ["错位", "反转", "像在看剧情"],
    hiddenDoubts: ["商品会不会硬插", "文化是不是只有风格"],
    likelyScrollReasons: ["场景不该这样拍", "人物动作像在闯关"],
    recognitionSignals: ["任务卡", "对峙构图", "鉴宝式观察"],
    commonScenes: ["浴室", "厨房", "办公室", "桌面"],
    compatibleIntentTypes: ["creative_first"],
    compatibleCategories: ["personal_care", "cleaning", "food_beverage", "storage_home"],
    compatibleHookTypes: ["H2", "H3", "H7"],
    compatibleEventKinds: ["cultural_intrusion", "environment_mismatch", "scale_inversion"],
    exampleAudienceInputs: ["睡前刷牙像闯关", "把收纳拍成通关"],
  },
]

export const ATTENTION_MICRO_PATTERNS: AttentionMicroPattern[] = [
  {
    id: "H1_A_TEXTURE_SHOCK",
    parentHookType: "H1",
    name: "质地冲击",
    attentionJob: "用质地变化抓住注意力",
    stopSignalLogic: "液体、泡沫、粉末、布料发生肉眼可见变化",
    tensionEngine: "观众想知道这个质地为什么这样变化",
    curiosityEngine: "变化原因后置到商品动作",
    bestForIntentModes: ["offer_first", "creative_first"],
    compatibleProductRoles: ["sensory_trigger", "evidence_object"],
    preferredProductEntryTiming: "first_second",
    eventQueryTags: ["texture_change", "macro_motion", "material_reveal"],
    preferredShotFunctions: ["macro_evidence", "hand_action_closeup"],
    preferredSoundFunctions: ["asmr_detail"],
    preferredOverlayFunctions: ["sensory_label"],
    goodForProductTraits: ["texture", "foam", "material"],
    weakForProductTraits: ["abstract_service"],
    commonFailureModes: ["only_packshot", "abstract_texture"],
    guardrailNotes: ["质地变化必须能被视频模型稳定表现"],
  },
  {
    id: "H2_A_DAILY_ACTION_FAILURE",
    parentHookType: "H2",
    name: "日常动作失败",
    attentionJob: "让熟悉动作突然失败",
    stopSignalLogic: "本该顺利的动作卡住或重复失败",
    tensionEngine: "重复失败、尴尬、时间压力",
    curiosityEngine: "观众想看如何换一种方法",
    bestForIntentModes: ["pain_first", "creative_first"],
    compatibleProductRoles: ["solution_clue", "contrast_object"],
    preferredProductEntryTiming: "early_1_2_5s",
    eventQueryTags: ["repeated_failure", "action_failure", "unfinished_action"],
    preferredShotFunctions: ["reaction_cut", "handheld_closeup"],
    preferredSoundFunctions: ["small_pause"],
    preferredOverlayFunctions: ["failure_count"],
    goodForProductTraits: ["problem_solver", "routine"],
    weakForProductTraits: ["pure_status_symbol"],
    commonFailureModes: ["conflict_too_large", "product_hard_cut"],
    guardrailNotes: ["失败必须安全可控"],
  },
  {
    id: "H3_D_RESULT_FIRST_CAUSE_LATER",
    parentHookType: "H3",
    name: "结果先行",
    attentionJob: "先给结果，不讲原因",
    stopSignalLogic: "观众看到变化后状态",
    tensionEngine: "原因缺失",
    curiosityEngine: "为什么会这样",
    bestForIntentModes: ["pain_first", "offer_first", "creative_first"],
    compatibleProductRoles: ["evidence_object", "reveal_anchor"],
    preferredProductEntryTiming: "middle_2_5_5s",
    eventQueryTags: ["result_first", "before_after_missing_cause"],
    preferredShotFunctions: ["match_cut", "partial_compare"],
    preferredSoundFunctions: ["reveal_hit"],
    preferredOverlayFunctions: ["question_gap"],
    goodForProductTraits: ["visible_result"],
    weakForProductTraits: ["invisible_benefit"],
    commonFailureModes: ["answer_too_early", "subtitle_only_gap"],
    guardrailNotes: ["缺口必须和商品承接有关"],
  },
  {
    id: "H4_B_SCENE_RECOGNITION",
    parentHookType: "H4",
    name: "场景识别",
    attentionJob: "让观众觉得这是自己的场景",
    stopSignalLogic: "熟悉生活节点被直接点中",
    tensionEngine: "日常流程正在卡住",
    curiosityEngine: "这一步为什么总出问题",
    bestForIntentModes: ["audience_first", "pain_first"],
    compatibleProductRoles: ["ritual_object", "solution_clue", "social_signal"],
    preferredProductEntryTiming: "early_1_2_5s",
    eventQueryTags: ["threshold_event", "routine_friction"],
    preferredShotFunctions: ["threshold_scene", "mirror_check"],
    preferredSoundFunctions: ["ambient_realism"],
    preferredOverlayFunctions: ["audience_callout"],
    goodForProductTraits: ["routine", "daily_use"],
    weakForProductTraits: ["rare_use"],
    commonFailureModes: ["audience_label_without_scene"],
    guardrailNotes: ["用场景识别代替空泛人群标签"],
  },
  {
    id: "H5_D_ONE_ACTION_PROOF",
    parentHookType: "H5",
    name: "一次动作证明",
    attentionJob: "让一个动作直接形成可见证据",
    stopSignalLogic: "动作前后差异清晰",
    tensionEngine: "观众判断这是否可信",
    curiosityEngine: "一次动作为什么能带来变化",
    bestForIntentModes: ["pain_first", "offer_first"],
    compatibleProductRoles: ["evidence_object", "before_after_anchor"],
    preferredProductEntryTiming: "first_second",
    eventQueryTags: ["single_action_demo", "process_trace"],
    preferredShotFunctions: ["macro_evidence", "fixed_before_after"],
    preferredSoundFunctions: ["action_sync"],
    preferredOverlayFunctions: ["proof_label"],
    goodForProductTraits: ["visible_result", "demoable"],
    weakForProductTraits: ["pure_brand"],
    commonFailureModes: ["magic_claim", "fake_before_after"],
    guardrailNotes: ["避免绝对化证明"],
  },
  {
    id: "H6_A_FRIEND_GRABS",
    parentHookType: "H6",
    name: "朋友抢先拿走",
    attentionJob: "用旁人反应制造社交信号",
    stopSignalLogic: "商品刚出现就被别人注意或拿走",
    tensionEngine: "主角还没解释，别人先行动",
    curiosityEngine: "为什么别人想试",
    bestForIntentModes: ["audience_first", "offer_first"],
    compatibleProductRoles: ["social_signal", "evidence_object"],
    preferredProductEntryTiming: "early_1_2_5s",
    eventQueryTags: ["friend_grabs", "group_reaction"],
    preferredShotFunctions: ["grab_action", "reaction_closeup"],
    preferredSoundFunctions: ["social_interrupt"],
    preferredOverlayFunctions: ["comment_style"],
    goodForProductTraits: ["shareable", "value_pack"],
    weakForProductTraits: ["private_use_only"],
    commonFailureModes: ["fake_review", "overacting"],
    guardrailNotes: ["避免假评价口吻"],
  },
  {
    id: "H7_A_MYTH_CHARACTER_LOGIC",
    parentHookType: "H7",
    name: "神话角色动作逻辑",
    attentionJob: "用具体文化动作制造识别和错位",
    stopSignalLogic: "日常动作被改写成闯关、识别、破局",
    tensionEngine: "文化符号进入现代小问题",
    curiosityEngine: "商品如何成为动作链里的道具",
    bestForIntentModes: ["creative_first"],
    compatibleProductRoles: ["unexpected_tool", "ritual_object", "reveal_anchor"],
    preferredProductEntryTiming: "first_second",
    eventQueryTags: ["cultural_intrusion", "ritual_mismatch"],
    preferredShotFunctions: ["cultural_insert", "task_complete"],
    preferredSoundFunctions: ["motif_sound"],
    preferredOverlayFunctions: ["quest_label"],
    goodForProductTraits: ["storyable", "daily_use"],
    weakForProductTraits: ["strict_professional_claim"],
    commonFailureModes: ["culture_as_style_only", "product_not_in_action"],
    guardrailNotes: ["文化必须改写动作链，不只是背景"],
  },
]

export const EVENT_PRIMITIVES: EventPrimitive[] = [
  { id: "EVT_RPF_001", name: "连续失败计数", eventKind: "repeated_failure", eventTemplate: "{person} 第三次尝试 {routineAction} 仍然失败，动作停住", productVisibility: "none", compatibleMicroPatternIds: ["H2_A_DAILY_ACTION_FAILURE"], recommendedProductRoles: ["solution_clue", "contrast_object"], shotTags: ["reaction_cut", "handheld_closeup"], compatibleIntentTypes: ["pain_first", "creative_first"] },
  { id: "EVT_BLK_001", name: "动作被阻止", eventKind: "blocked_action", eventTemplate: "{person} 正要继续旧方法，被旁人或物体轻轻阻止", productVisibility: "background_hint", compatibleMicroPatternIds: ["H2_A_DAILY_ACTION_FAILURE", "H4_B_SCENE_RECOGNITION"], recommendedProductRoles: ["solution_clue", "reveal_anchor"], shotTags: ["hand_blocking", "reaction_cut"], compatibleIntentTypes: ["pain_first", "audience_first"] },
  { id: "EVT_THR_003", name: "睡前最后一步", eventKind: "threshold_event", eventTemplate: "灯已经关了一半，{routine} 还没完成，人物停住", productVisibility: "none", compatibleMicroPatternIds: ["H4_B_SCENE_RECOGNITION", "H2_A_DAILY_ACTION_FAILURE"], recommendedProductRoles: ["solution_clue", "ritual_object"], shotTags: ["bedtime_threshold", "doorway_stop"], compatibleIntentTypes: ["audience_first", "pain_first", "creative_first"] },
  { id: "EVT_HND_001", name: "递出被拒绝", eventKind: "handoff_refusal", eventTemplate: "{personA} 把 {routineObjectOrProduct} 递给 {personB}，对方后退或摆手", productVisibility: "clear_but_not_packshot", compatibleMicroPatternIds: ["H2_A_DAILY_ACTION_FAILURE", "H4_B_SCENE_RECOGNITION"], recommendedProductRoles: ["solution_clue", "sensory_trigger"], shotTags: ["handoff_refusal", "reaction_closeup"], compatibleIntentTypes: ["audience_first", "pain_first"] },
  { id: "EVT_CUL_001", name: "神话道具进入日常", eventKind: "cultural_intrusion", eventTemplate: "普通 {dailyScene} 里突然出现一个借用神话功能的道具线索", productVisibility: "partial", compatibleMicroPatternIds: ["H7_A_MYTH_CHARACTER_LOGIC"], recommendedProductRoles: ["unexpected_tool", "solution_clue"], shotTags: ["cultural_insert", "ritual_handoff"], compatibleIntentTypes: ["creative_first"] },
  { id: "EVT_RIT_005", name: "通关动作", eventKind: "ritual_task", eventTemplate: "人物完成一个小任务后，商品被放到完成区或下一关位置", productVisibility: "clear_but_not_packshot", compatibleMicroPatternIds: ["H7_A_MYTH_CHARACTER_LOGIC", "H5_D_ONE_ACTION_PROOF"], recommendedProductRoles: ["ritual_object", "evidence_object"], shotTags: ["task_complete", "quest_label"], compatibleIntentTypes: ["creative_first", "offer_first"] },
  { id: "EVT_CMP_003", name: "旧方法 vs 新方法", eventKind: "comparison_split", eventTemplate: "旧方法失败镜头和新方法线索并排出现", productVisibility: "partial", compatibleMicroPatternIds: ["H5_D_ONE_ACTION_PROOF", "H2_A_DAILY_ACTION_FAILURE"], recommendedProductRoles: ["contrast_object", "solution_clue"], shotTags: ["side_by_side", "fixed_before_after"], compatibleIntentTypes: ["pain_first", "offer_first"] },
  { id: "EVT_TRF_001", name: "乱到整齐", eventKind: "object_transformation", eventTemplate: "{messyObjects} 在一个动作后从散乱变得有序，先只展示局部", productVisibility: "clear_but_not_packshot", compatibleMicroPatternIds: ["H5_D_ONE_ACTION_PROOF", "H4_B_SCENE_RECOGNITION"], recommendedProductRoles: ["before_after_anchor", "evidence_object"], shotTags: ["state_change", "match_cut"], compatibleIntentTypes: ["pain_first", "offer_first"] },
  { id: "EVT_EVD_002", name: "近景证据发现", eventKind: "evidence_closeup", eventTemplate: "镜头贴近一个平时看不清的细节，显示变化边界", productVisibility: "partial", compatibleMicroPatternIds: ["H1_A_TEXTURE_SHOCK", "H5_D_ONE_ACTION_PROOF", "H3_D_RESULT_FIRST_CAUSE_LATER"], recommendedProductRoles: ["evidence_object", "before_after_anchor"], shotTags: ["macro_evidence", "track_reveal"], compatibleIntentTypes: ["pain_first", "offer_first", "creative_first"] },
  { id: "EVT_VAL_001", name: "数量价值摊开", eventKind: "value_visualization", eventTemplate: "{bundleOrQuantity} 被摊开成一眼能看懂的数量差", productVisibility: "hero_visible", compatibleMicroPatternIds: ["H6_A_FRIEND_GRABS", "H5_D_ONE_ACTION_PROOF"], recommendedProductRoles: ["evidence_object", "social_signal"], shotTags: ["top_down_value", "stack_visualization"], compatibleIntentTypes: ["offer_first"] },
  { id: "EVT_ENV_003", name: "浴室像战场/擂台", eventKind: "environment_mismatch", eventTemplate: "浴室或厨房被拍成一个小对决场景", productVisibility: "none", compatibleMicroPatternIds: ["H7_A_MYTH_CHARACTER_LOGIC", "H2_A_DAILY_ACTION_FAILURE"], recommendedProductRoles: ["unexpected_tool", "solution_clue"], shotTags: ["duel_space", "genre_reframe"], compatibleIntentTypes: ["creative_first"] },
  { id: "EVT_HND_003", name: "被旁人拿走", eventKind: "handoff_grab", eventTemplate: "{product} 刚放下，旁边人直接拿走或试用", productVisibility: "clear_but_not_packshot", compatibleMicroPatternIds: ["H6_A_FRIEND_GRABS"], recommendedProductRoles: ["social_signal"], shotTags: ["grab_action", "social_interrupt"], compatibleIntentTypes: ["audience_first", "offer_first"] },
]

export const PRODUCT_BRIDGE_ROLES: ProductBridgeRoleResource[] = [
  {
    id: "BRIDGE_SOLUTION_CLUE",
    role: "solution_clue",
    name: "解决线索",
    definition: "商品作为换一种方法的线索进入，而不是直接介绍",
    bestForHookTypes: ["H2", "H3", "H4", "H7"],
    bestForIntentModes: ["pain_first", "audience_first", "creative_first"],
    bestForProductCategoryTags: ["personal_care", "cleaning", "storage_home", "mother_baby"],
    entryTimingRules: ["2.0s-4.0s 进入最自然", "进入前必须有失败、犹豫或卡住"],
    requiredPreEntryTension: ["重复尝试失败", "动作被迫停止", "普通方法不奏效"],
    entryActionTemplates: ["人物停止解释，转而拿出 {product} 做一个小动作", "{product} 作为新的尝试入口出现"],
    compatibleEventKinds: ["repeated_failure", "blocked_action", "threshold_event"],
    compatibleProofTags: ["failure_contrast", "single_action_demo"],
    compatibleCulturalMotifTypes: ["myth_tool", "quest_item"],
    recommendedShotIds: ["SHOT_HAND_ACTION_CLOSEUP", "SHOT_REACTION_CUT"],
    textOverlaySyntaxHints: ["先别急着放弃", "问题可能不在这一步"],
    soundHints: ["轻微停顿", "动作重新开始的短提示音"],
    avoidHardSellRules: ["entryAction 不能是展示商品/介绍商品"],
    validatorChecks: ["必须有 preEntryTension", "商品进入必须改变前一个动作走向"],
  },
  {
    id: "BRIDGE_EVIDENCE_OBJECT",
    role: "evidence_object",
    name: "证据物",
    definition: "商品作为看得见的证据进入",
    bestForHookTypes: ["H1", "H3", "H5", "H6"],
    bestForIntentModes: ["pain_first", "offer_first"],
    bestForProductCategoryTags: ["cleaning", "beauty", "food_beverage", "storage_home"],
    entryTimingRules: ["证据要在 1-3 秒内出现", "同一主体或同一动作前后对照"],
    requiredPreEntryTension: ["怀疑", "失败", "看不见的细节"],
    entryActionTemplates: ["镜头先拍变化边界，再带到 {product}", "{product} 出现在证据旁边而非硬切"],
    compatibleEventKinds: ["evidence_closeup", "comparison_split", "object_transformation"],
    compatibleProofTags: ["before_after", "closeup_evidence", "single_action_demo"],
    compatibleCulturalMotifTypes: ["appraisal", "trial"],
    recommendedShotIds: ["SHOT_MACRO_EVIDENCE", "SHOT_FIXED_BEFORE_AFTER"],
    textOverlaySyntaxHints: ["差别在这里", "先看这一块"],
    soundHints: ["动作同步音", "短促发现音"],
    avoidHardSellRules: ["不能只说效果明显"],
    validatorChecks: ["必须有可见证据", "避免绝对化功效"],
  },
  {
    id: "BRIDGE_CONTRAST_OBJECT",
    role: "contrast_object",
    name: "反差物",
    definition: "商品作为旧方法/新方法、前后状态的反差锚点",
    bestForHookTypes: ["H2", "H5", "H7"],
    bestForIntentModes: ["pain_first", "offer_first", "creative_first"],
    bestForProductCategoryTags: ["cleaning", "storage_home", "kitchen_tools", "womenswear"],
    entryTimingRules: ["对比双方要同框或同机位", "反差不能踩竞品"],
    requiredPreEntryTension: ["旧方法失败", "价值不清楚", "选择困难"],
    entryActionTemplates: ["旧方法停住，新方法线索被放在旁边", "{product} 与混乱/失败状态形成稳定反差"],
    compatibleEventKinds: ["comparison_split", "environment_mismatch"],
    compatibleProofTags: ["failure_contrast", "side_by_side"],
    compatibleCulturalMotifTypes: ["duel", "challenge"],
    recommendedShotIds: ["SHOT_SIDE_BY_SIDE", "SHOT_MATCH_CUT"],
    textOverlaySyntaxHints: ["同一个问题，两种结果", "别急着换下一步"],
    soundHints: ["左右切换音", "停顿后进入"],
    avoidHardSellRules: ["不要虚构竞品或价格"],
    validatorChecks: ["反差必须可见", "不能攻击用户或竞品"],
  },
  {
    id: "BRIDGE_UNEXPECTED_TOOL",
    role: "unexpected_tool",
    name: "异常工具",
    definition: "商品成为剧情或文化动作链里的意外工具",
    bestForHookTypes: ["H3", "H7"],
    bestForIntentModes: ["creative_first"],
    bestForProductCategoryTags: ["personal_care", "cleaning", "food_beverage", "digital_accessories"],
    entryTimingRules: ["进入越早越需要动作解释", "必须回收前面的错位"],
    requiredPreEntryTension: ["场景错位", "任务卡住", "文化动作等待道具"],
    entryActionTemplates: ["{product} 像通关道具一样被递出", "{product} 解释前面反常动作"],
    compatibleEventKinds: ["cultural_intrusion", "environment_mismatch", "ritual_task"],
    compatibleProofTags: ["reveal_anchor"],
    compatibleCulturalMotifTypes: ["myth_tool", "genre_tool"],
    recommendedShotIds: ["SHOT_CULTURAL_INSERT", "SHOT_RITUAL_HANDOFF"],
    textOverlaySyntaxHints: ["这一关缺的不是勇气", "道具出现"],
    soundHints: ["任务提示音", "鼓点加速"],
    avoidHardSellRules: ["不能只把商品放进文化背景"],
    validatorChecks: ["商品必须参与动作链"],
  },
  {
    id: "BRIDGE_SOCIAL_SIGNAL",
    role: "social_signal",
    name: "社交信号",
    definition: "商品通过他人反应、抢用、围观进入",
    bestForHookTypes: ["H4", "H6"],
    bestForIntentModes: ["audience_first", "offer_first"],
    bestForProductCategoryTags: ["food_beverage", "beauty", "pet", "womenswear"],
    entryTimingRules: ["旁人反应先于解释", "不要假评价"],
    requiredPreEntryTension: ["质疑", "旁人停住", "被拿走"],
    entryActionTemplates: ["旁人不解释直接拿走 {product}", "朋友看到后伸手试用"],
    compatibleEventKinds: ["handoff_grab", "group_reaction"],
    compatibleProofTags: ["social_reaction"],
    compatibleCulturalMotifTypes: ["group_ritual"],
    recommendedShotIds: ["SHOT_GRAB_ACTION", "SHOT_REACTION_CLOSEUP"],
    textOverlaySyntaxHints: ["他先拿走了", "旁边人停住"],
    soundHints: ["环境声", "短促打断音"],
    avoidHardSellRules: ["不写虚假评论"],
    validatorChecks: ["反应必须由动作触发"],
  },
  {
    id: "BRIDGE_RITUAL_OBJECT",
    role: "ritual_object",
    name: "仪式物",
    definition: "商品嵌入日常或文化仪式步骤",
    bestForHookTypes: ["H4", "H7"],
    bestForIntentModes: ["audience_first", "creative_first"],
    bestForProductCategoryTags: ["personal_care", "mother_baby", "food_beverage", "womenswear"],
    entryTimingRules: ["进入要跟流程节点绑定", "不能只摆拍"],
    requiredPreEntryTension: ["流程卡住", "任务未完成", "仪式等待下一步"],
    entryActionTemplates: ["{product} 被放到下一步位置", "人物像完成仪式一样拿起 {product}"],
    compatibleEventKinds: ["threshold_event", "ritual_task"],
    compatibleProofTags: ["context_fit"],
    compatibleCulturalMotifTypes: ["quest", "festival"],
    recommendedShotIds: ["SHOT_TASK_COMPLETE", "SHOT_RITUAL_HANDOFF"],
    textOverlaySyntaxHints: ["最后一步", "下一关"],
    soundHints: ["提示音", "轻快环境声"],
    avoidHardSellRules: ["不要变成单独 packshot"],
    validatorChecks: ["商品必须属于流程"],
  },
  {
    id: "BRIDGE_SENSORY_TRIGGER",
    role: "sensory_trigger",
    name: "感官触发物",
    definition: "商品通过气味、口感、质地、声音或触感触发停顿和反应",
    bestForHookTypes: ["H1", "H3", "H6"],
    bestForIntentModes: ["audience_first", "offer_first", "creative_first"],
    bestForProductCategoryTags: ["beauty", "food_beverage", "personal_care", "womenswear"],
    entryTimingRules: ["感官动作必须在 0-2 秒内可见", "反应必须来自打开、喷洒、挤出、触摸、入口前等动作"],
    requiredPreEntryTension: ["人物突然停住", "旁人靠近", "质地或声音引发注意"],
    entryActionTemplates: ["人物打开 {product} 后，旁人先停住或转头", "{product} 的质地/声音/气味通过动作触发反应"],
    compatibleEventKinds: ["evidence_closeup", "handoff_refusal", "handoff_grab"],
    compatibleProofTags: ["sensory_reaction", "closeup_evidence"],
    compatibleCulturalMotifTypes: ["ritual", "appraisal"],
    recommendedShotIds: ["SHOT_HAND_ACTION_CLOSEUP", "SHOT_REACTION_CLOSEUP", "SHOT_MACRO_EVIDENCE"],
    textOverlaySyntaxHints: ["先别说，先看反应", "打开这一秒"],
    soundHints: ["轻微开盖音", "ASMR 细节声", "旁人停顿"],
    avoidHardSellRules: ["不能只写很香/很好吃/很高级", "不可把不可见感官写成绝对效果"],
    validatorChecks: ["必须有感官触发动作", "必须有可见反应或近景证据"],
  },
  {
    id: "BRIDGE_BEFORE_AFTER_ANCHOR",
    role: "before_after_anchor",
    name: "前后对比锚点",
    definition: "商品把同一主体的前后差异锁在一个可比动作或机位里",
    bestForHookTypes: ["H3", "H5", "H2"],
    bestForIntentModes: ["pain_first", "offer_first"],
    bestForProductCategoryTags: ["cleaning", "storage_home", "beauty", "kitchen_tools", "womenswear"],
    entryTimingRules: ["前后主体必须一致", "对比应在 1-4 秒内形成，不夸大无法证明的结果"],
    requiredPreEntryTension: ["旧状态可见", "旧方法卡住", "观众能判断差异"],
    entryActionTemplates: ["固定机位先拍旧状态，{product} 介入后保留同一参照物", "{product} 与变化边界同框"],
    compatibleEventKinds: ["comparison_split", "object_transformation", "evidence_closeup"],
    compatibleProofTags: ["before_after", "single_action_demo", "failure_contrast"],
    compatibleCulturalMotifTypes: ["challenge", "trial"],
    recommendedShotIds: ["SHOT_FIXED_BEFORE_AFTER", "SHOT_MATCH_CUT", "SHOT_SIDE_BY_SIDE"],
    textOverlaySyntaxHints: ["同一个位置，看边界", "前后不要换机位"],
    soundHints: ["match cut", "短促对比音"],
    avoidHardSellRules: ["不要制造虚假前后效果", "不要攻击竞品"],
    validatorChecks: ["必须能看出同一主体", "对比必须和商品动作有关"],
  },
  {
    id: "BRIDGE_REVEAL_ANCHOR",
    role: "reveal_anchor",
    name: "揭示锚点",
    definition: "商品解释前一秒的异常、结果或文化动作，而不是最后才硬露出",
    bestForHookTypes: ["H3", "H7", "H1"],
    bestForIntentModes: ["creative_first", "offer_first", "pain_first"],
    bestForProductCategoryTags: ["beauty", "digital_accessories", "food_beverage", "personal_care"],
    entryTimingRules: ["悬念不能拖到片尾", "商品出现后要回收前面的异常动作"],
    requiredPreEntryTension: ["先看到结果", "先听到声音", "先看到不合常理的动作"],
    entryActionTemplates: ["镜头后移，揭示刚才动作的原因是 {product}", "{product} 作为答案进入，但仍参与动作"],
    compatibleEventKinds: ["evidence_closeup", "cultural_intrusion", "blocked_action"],
    compatibleProofTags: ["reveal_anchor", "context_fit"],
    compatibleCulturalMotifTypes: ["myth_tool", "genre_tool", "appraisal"],
    recommendedShotIds: ["SHOT_CULTURAL_INSERT", "SHOT_MATCH_CUT", "SHOT_HAND_ACTION_CLOSEUP"],
    textOverlaySyntaxHints: ["原因在这一步", "刚才不是特效"],
    soundHints: ["揭示音", "镜头后移的停顿"],
    avoidHardSellRules: ["不能让商品只承担答案字幕", "揭示后必须继续有动作"],
    validatorChecks: ["必须回收前置好奇缺口", "商品不能只是静态答案"],
  },
]

export const PROOF_VISUALIZATION_CARDS: ProofVisualizationCard[] = [
  { id: "PROOF_FAILURE_CONTRAST", claimTag: "failure_contrast", abstractClaim: "旧方法不够顺", claimFamily: "effectiveness", bestProofModes: ["PM_FAILURE_CONTRAST", "PM_SIDE_BY_SIDE_COMPARISON"], visualProofs: ["旧方法失败后停住"], usageProofs: ["同一动作换入口"], closeUpProofs: ["失败细节近景"], comparisonProofs: ["旧方法 vs 新方法"], reactionProofs: ["人物停住"], compatibleIntentModes: ["pain_first"], compatibleHookTypes: ["H2", "H5"], compatibleMicroPatterns: ["H2_A_DAILY_ACTION_FAILURE"], compatibleProductRoles: ["solution_clue", "contrast_object"], compatibleEventKinds: ["repeated_failure", "comparison_split"], recommendedShotIds: ["SHOT_SIDE_BY_SIDE", "SHOT_REACTION_CUT"], recommendedShotTags: ["side_by_side", "reaction_cut"], complianceRiskTags: ["avoid_competitor_attack"], modelFeasibilityRiskTags: ["keep_action_simple"], goodHookUsage: "第三次失败后，商品作为新尝试入口出现" },
  { id: "PROOF_CLOSEUP_EVIDENCE", claimTag: "closeup_evidence", abstractClaim: "细节看得见", claimFamily: "effectiveness", bestProofModes: ["PM_CLOSEUP_EVIDENCE"], visualProofs: ["变化边界"], usageProofs: ["手部操作"], closeUpProofs: ["微距细节"], comparisonProofs: ["局部前后"], reactionProofs: ["手停半秒"], compatibleIntentModes: ["pain_first", "offer_first", "creative_first"], compatibleHookTypes: ["H1", "H3", "H5"], compatibleMicroPatterns: ["H1_A_TEXTURE_SHOCK", "H5_D_ONE_ACTION_PROOF"], compatibleProductRoles: ["evidence_object"], compatibleEventKinds: ["evidence_closeup"], recommendedShotIds: ["SHOT_MACRO_EVIDENCE"], recommendedShotTags: ["macro_evidence"], complianceRiskTags: ["avoid_absolute_effect"], modelFeasibilityRiskTags: ["small_detail_risk"], goodHookUsage: "镜头贴近残留/泡沫/质地变化，而不是字幕说有效" },
  { id: "PROOF_VALUE_QUANTITY", claimTag: "value_quantity", abstractClaim: "优惠/组合价值可见", claimFamily: "value", bestProofModes: ["PM_QUANTITY_SCALE", "PM_VALUE_BREAKDOWN"], visualProofs: ["数量摊开"], usageProofs: ["组合被同时拿起"], closeUpProofs: ["赠品/规格近景"], comparisonProofs: ["单件 vs 组合"], reactionProofs: ["旁人拿走"], compatibleIntentModes: ["offer_first"], compatibleHookTypes: ["H5", "H6"], compatibleMicroPatterns: ["H6_A_FRIEND_GRABS"], compatibleProductRoles: ["evidence_object", "social_signal"], compatibleEventKinds: ["value_visualization", "handoff_grab"], recommendedShotIds: ["SHOT_TOP_DOWN_VALUE"], recommendedShotTags: ["top_down_value"], complianceRiskTags: ["use_user_offer_only"], modelFeasibilityRiskTags: ["quantity_scale_risk"], goodHookUsage: "把第二件/组合用数量摆出来，不编造价格" },
  { id: "PROOF_CONTEXT_FIT", claimTag: "context_fit", abstractClaim: "它属于这个场景", claimFamily: "convenience", bestProofModes: ["PM_CONTEXT_FIT", "PM_REVEAL_ANCHOR"], visualProofs: ["商品自然处在生活节点"], usageProofs: ["流程里顺手拿起"], closeUpProofs: ["位置/尺寸"], comparisonProofs: [], reactionProofs: ["人物没解释但动作继续"], compatibleIntentModes: ["audience_first", "creative_first"], compatibleHookTypes: ["H4", "H7"], compatibleMicroPatterns: ["H4_B_SCENE_RECOGNITION", "H7_A_MYTH_CHARACTER_LOGIC"], compatibleProductRoles: ["ritual_object", "solution_clue"], compatibleEventKinds: ["threshold_event", "ritual_task"], recommendedShotIds: ["SHOT_THRESHOLD_SCENE"], recommendedShotTags: ["threshold_scene"], complianceRiskTags: ["avoid_overclaim"], modelFeasibilityRiskTags: ["scene_clarity"], goodHookUsage: "商品在睡前/出门前流程中自然成为下一步" },
  { id: "PROOF_SENSORY_REACTION", claimTag: "sensory_reaction", abstractClaim: "气味/口感/质地让人停住", claimFamily: "sensory", bestProofModes: ["PM_SENSORY_REACTION", "PM_ASMR_DETAIL"], visualProofs: ["闻到/摸到/咬到后的停顿"], usageProofs: ["打开或挤出动作"], closeUpProofs: ["质地/包装开启"], comparisonProofs: [], reactionProofs: ["人物转头或靠近"], compatibleIntentModes: ["audience_first", "offer_first", "creative_first"], compatibleHookTypes: ["H1", "H3", "H6"], compatibleMicroPatterns: ["H1_A_TEXTURE_SHOCK"], compatibleProductRoles: ["sensory_trigger", "social_signal"], compatibleEventKinds: ["evidence_closeup", "handoff_grab"], recommendedShotIds: ["SHOT_HAND_ACTION_CLOSEUP"], recommendedShotTags: ["hand_action_closeup"], complianceRiskTags: ["avoid_invisible_claim"], modelFeasibilityRiskTags: ["smell_invisible"], goodHookUsage: "先拍动作和反应，不空说很香很好吃" },
  { id: "PROOF_EFFICIENCY_ONE_ACTION", claimTag: "efficiency_one_action", abstractClaim: "少一步/更顺手", claimFamily: "efficiency", bestProofModes: ["PM_PROCESS_TRACE", "PM_SINGLE_ACTION_DEMO", "PM_BEFORE_AFTER"], visualProofs: ["旧动作停住，新动作一次完成"], usageProofs: ["单手完成或流程少一步"], closeUpProofs: ["关键连接/开合/收纳动作"], comparisonProofs: ["旧流程 vs 新流程"], reactionProofs: ["人物停住后继续动作"], compatibleIntentModes: ["pain_first", "audience_first", "offer_first"], compatibleHookTypes: ["H2", "H4", "H5"], compatibleMicroPatterns: ["H2_A_DAILY_ACTION_FAILURE", "H4_B_SCENE_RECOGNITION", "H5_D_ONE_ACTION_PROOF"], compatibleProductRoles: ["solution_clue", "before_after_anchor", "ritual_object"], compatibleEventKinds: ["repeated_failure", "threshold_event", "object_transformation"], recommendedShotIds: ["SHOT_HAND_ACTION_CLOSEUP", "SHOT_TASK_COMPLETE"], recommendedShotTags: ["hand_action_closeup", "task_complete"], complianceRiskTags: ["avoid_exact_time_claim"], modelFeasibilityRiskTags: ["keep_sequence_short"], goodHookUsage: "先让旧流程卡一下，再用一个可见动作让流程继续" },
  { id: "PROOF_QUALITY_MATERIAL", claimTag: "quality_material", abstractClaim: "材质/做工/质感可见", claimFamily: "quality", bestProofModes: ["PM_CLOSEUP_EVIDENCE", "PM_SENSORY_REACTION", "PM_REVEAL_ANCHOR"], visualProofs: ["材质纹理、边缘、光泽或结构细节"], usageProofs: ["手部触摸、拿起、开合"], closeUpProofs: ["纹理/接口/瓶身/布料近景"], comparisonProofs: [], reactionProofs: ["人物靠近观察或手停半秒"], compatibleIntentModes: ["audience_first", "offer_first", "creative_first"], compatibleHookTypes: ["H1", "H3", "H6"], compatibleMicroPatterns: ["H1_A_TEXTURE_SHOCK", "H3_D_RESULT_FIRST_CAUSE_LATER"], compatibleProductRoles: ["sensory_trigger", "reveal_anchor", "social_signal"], compatibleEventKinds: ["evidence_closeup", "handoff_grab"], recommendedShotIds: ["SHOT_MACRO_EVIDENCE", "SHOT_REACTION_CLOSEUP"], recommendedShotTags: ["macro_evidence", "reaction_closeup"], complianceRiskTags: ["avoid_luxury_overclaim"], modelFeasibilityRiskTags: ["tiny_detail_risk"], goodHookUsage: "用手部近景和材质边界承接高级感，不用空说高级" },
  { id: "PROOF_TECH_FIT", claimTag: "tech_fit", abstractClaim: "适配/连接/支撑关系看得见", claimFamily: "tech", bestProofModes: ["PM_CONTEXT_FIT", "PM_SINGLE_ACTION_DEMO"], visualProofs: ["接口、磁吸、支架角度、设备位置稳定"], usageProofs: ["连接、吸附、支起、收纳"], closeUpProofs: ["接口/卡扣/支点近景"], comparisonProofs: ["使用前后桌面或设备状态"], reactionProofs: ["人物松手后设备保持状态"], compatibleIntentModes: ["pain_first", "audience_first", "creative_first"], compatibleHookTypes: ["H3", "H4", "H5"], compatibleMicroPatterns: ["H3_D_RESULT_FIRST_CAUSE_LATER", "H4_B_SCENE_RECOGNITION", "H5_D_ONE_ACTION_PROOF"], compatibleProductRoles: ["reveal_anchor", "solution_clue", "before_after_anchor"], compatibleEventKinds: ["blocked_action", "evidence_closeup", "object_transformation"], recommendedShotIds: ["SHOT_HAND_ACTION_CLOSEUP", "SHOT_FIXED_BEFORE_AFTER"], recommendedShotTags: ["hand_action_closeup", "fixed_before_after"], complianceRiskTags: ["avoid_unverified_compatibility"], modelFeasibilityRiskTags: ["device_brand_logo_risk"], goodHookUsage: "让连接或支撑动作解释痛点，而不是口播适配所有设备" },
]

export const SHOT_CARDS: ShotCard[] = [
  { id: "SHOT_REACTION_CUT", name: "反应切镜", shotFunction: "reaction", camera: "手持近景", composition: "脸/手/问题物三点切换", motion: "短促切换", productVisibilityRange: ["none", "partial"], compatibleEventKinds: ["repeated_failure", "blocked_action"], compatibleProductRoles: ["solution_clue", "social_signal"], compatibleProofModes: ["PM_FAILURE_CONTRAST"], modelRiskTags: ["overacting"] },
  { id: "SHOT_HAND_ACTION_CLOSEUP", name: "手部动作近景", shotFunction: "product_bridge", camera: "手持近景", composition: "手、商品、问题现场同框", motion: "小幅推进", productVisibilityRange: ["partial", "clear_but_not_packshot"], compatibleEventKinds: ["blocked_action", "handoff_refusal"], compatibleProductRoles: ["solution_clue", "ritual_object"], compatibleProofModes: ["PM_SINGLE_ACTION_DEMO"], modelRiskTags: ["hand_artifacts"] },
  { id: "SHOT_MACRO_EVIDENCE", name: "微距证据", shotFunction: "proof_hint", camera: "微距", composition: "变化边界占画面中心", motion: "缓慢推近", productVisibilityRange: ["partial"], compatibleEventKinds: ["evidence_closeup"], compatibleProductRoles: ["evidence_object"], compatibleProofModes: ["PM_CLOSEUP_EVIDENCE"], modelRiskTags: ["tiny_detail"] },
  { id: "SHOT_FIXED_BEFORE_AFTER", name: "固定前后对比", shotFunction: "proof_hint", camera: "固定机位", composition: "同一主体同一角度", motion: "match cut", productVisibilityRange: ["partial", "clear_but_not_packshot"], compatibleEventKinds: ["comparison_split", "object_transformation"], compatibleProductRoles: ["before_after_anchor", "evidence_object"], compatibleProofModes: ["PM_BEFORE_AFTER"], modelRiskTags: ["fake_before_after"] },
  { id: "SHOT_SIDE_BY_SIDE", name: "并排对照", shotFunction: "build_tension", camera: "俯拍或正面", composition: "左右同时开始", motion: "稳定分屏", productVisibilityRange: ["partial"], compatibleEventKinds: ["comparison_split"], compatibleProductRoles: ["contrast_object"], compatibleProofModes: ["PM_SIDE_BY_SIDE_COMPARISON"], modelRiskTags: ["split_screen_complexity"] },
  { id: "SHOT_TOP_DOWN_VALUE", name: "俯拍价值摊开", shotFunction: "proof_hint", camera: "俯拍", composition: "数量/组合整齐摊开", motion: "手部摆放", productVisibilityRange: ["hero_visible"], compatibleEventKinds: ["value_visualization"], compatibleProductRoles: ["evidence_object", "social_signal"], compatibleProofModes: ["PM_QUANTITY_SCALE", "PM_VALUE_BREAKDOWN"], modelRiskTags: ["quantity_hallucination"] },
  { id: "SHOT_THRESHOLD_SCENE", name: "临界场景", shotFunction: "stop_scroll", camera: "环境中近景", composition: "门口/镜前/床边的停顿", motion: "人物动作中断", productVisibilityRange: ["none", "background_hint"], compatibleEventKinds: ["threshold_event"], compatibleProductRoles: ["solution_clue", "ritual_object"], compatibleProofModes: ["PM_CONTEXT_FIT"], modelRiskTags: ["scene_ambiguity"] },
  { id: "SHOT_CULTURAL_INSERT", name: "文化道具闯入", shotFunction: "curiosity_gap", camera: "轻微推近", composition: "日常物与文化动作线索同框", motion: "道具进入画面", productVisibilityRange: ["partial", "clear_but_not_packshot"], compatibleEventKinds: ["cultural_intrusion", "environment_mismatch"], compatibleProductRoles: ["unexpected_tool", "ritual_object"], compatibleProofModes: ["PM_REVEAL_ANCHOR"], modelRiskTags: ["style_only_culture"] },
  { id: "SHOT_RITUAL_HANDOFF", name: "仪式性交接", shotFunction: "product_bridge", camera: "手部中近景", composition: "双手交接，商品清晰但非硬广", motion: "郑重递出", productVisibilityRange: ["clear_but_not_packshot"], compatibleEventKinds: ["ritual_task", "handoff_refusal"], compatibleProductRoles: ["ritual_object", "unexpected_tool"], compatibleProofModes: ["PM_CONTEXT_FIT"], modelRiskTags: ["packshot_bias"] },
  { id: "SHOT_TASK_COMPLETE", name: "任务完成区", shotFunction: "payoff", camera: "俯拍或固定近景", composition: "商品进入完成区/下一关", motion: "放下/推进", productVisibilityRange: ["clear_but_not_packshot", "hero_visible"], compatibleEventKinds: ["ritual_task", "object_transformation"], compatibleProductRoles: ["ritual_object", "evidence_object"], compatibleProofModes: ["PM_PROCESS_TRACE"], modelRiskTags: ["game_ui_text"] },
  { id: "SHOT_MATCH_CUT", name: "匹配切换", shotFunction: "reveal_or_compare", camera: "固定或轻推", composition: "同一主体保持位置，动作前后衔接", motion: "match cut", productVisibilityRange: ["partial", "clear_but_not_packshot"], compatibleEventKinds: ["comparison_split", "evidence_closeup", "cultural_intrusion"], compatibleProductRoles: ["before_after_anchor", "reveal_anchor", "contrast_object"], compatibleProofModes: ["PM_BEFORE_AFTER", "PM_REVEAL_ANCHOR"], modelRiskTags: ["continuity_drift"] },
  { id: "SHOT_GRAB_ACTION", name: "伸手拿走", shotFunction: "social_signal", camera: "桌面中近景", composition: "商品在共享空间，旁人手进入画面", motion: "快速伸手拿走", productVisibilityRange: ["clear_but_not_packshot", "hero_visible"], compatibleEventKinds: ["handoff_grab", "value_visualization"], compatibleProductRoles: ["social_signal", "evidence_object"], compatibleProofModes: ["PM_SENSORY_REACTION", "PM_QUANTITY_SCALE"], modelRiskTags: ["hand_artifacts"] },
  { id: "SHOT_REACTION_CLOSEUP", name: "反应近景", shotFunction: "reaction", camera: "脸/手部近景", composition: "表情、手部停顿和商品线索在连续切镜中出现", motion: "短促推近或停顿", productVisibilityRange: ["none", "partial"], compatibleEventKinds: ["handoff_grab", "evidence_closeup", "handoff_refusal"], compatibleProductRoles: ["social_signal", "sensory_trigger", "reveal_anchor"], compatibleProofModes: ["PM_SENSORY_REACTION", "PM_CLOSEUP_EVIDENCE"], modelRiskTags: ["overacting"] },
]

export const CONSTRAINT_RULES: ConstraintRule[] = [
  { id: "CONSTRAINT_PRODUCT_LOCK", severity: "hard", rule: "商品外形、包装和使用动作不能被替换成其它品类", appliesTo: ["product", "provider"] },
  { id: "CONSTRAINT_NO_PACKSHOT_ONLY", severity: "hard", rule: "Hook 前段不能只展示 packshot，必须有动作或事件", appliesTo: ["script", "shot"] },
  { id: "CONSTRAINT_BRIDGE_REQUIRED", severity: "hard", rule: "商品出现必须承担 bridge role，不能硬切广告展示", appliesTo: ["product", "script"] },
  { id: "CONSTRAINT_CULTURE_ACTION", severity: "hard", rule: "文化元素必须改写动作链，不能只是背景/滤镜/服装风格", appliesTo: ["culture", "script"] },
  { id: "CONSTRAINT_NO_ABSOLUTE_CLAIM", severity: "hard", rule: "避免绝对化、医疗化、无法证明的功效承诺", appliesTo: ["proof", "script"] },
  { id: "CONSTRAINT_VISIBLE_EVENT", severity: "hard", rule: "第一秒必须有可见事件，不能只靠字幕说悬念", appliesTo: ["script", "shot"] },
  { id: "CONSTRAINT_PROVIDER_SIMPLE_PHYSICS", severity: "soft", rule: "避免要求视频模型生成复杂不稳定物理变化", appliesTo: ["provider", "shot"] },
  { id: "CONSTRAINT_CHINESE_USER_INTENT", severity: "hard", rule: "用户中文意图必须进入创意假设和商品承接", appliesTo: ["script"] },
]

export const FAILURE_MODES: FailureMode[] = [
  { id: "FAIL_PRODUCT_DRIFT", warning: "商品被模型替换成相似但错误的品类", repairHint: "增加 visualAnchors 和 forbiddenVisualConfusions", appliesTo: ["product", "provider"] },
  { id: "FAIL_ABSTRACT_HOOK", warning: "只写痛点/卖点，没有具体第一秒事件", repairHint: "强制选择 Event Primitive 并写出 subject/action", appliesTo: ["script", "shot"] },
  { id: "FAIL_HARD_SELL_BRIDGE", warning: "前面有剧情，商品突然硬切展示", repairHint: "选择 bridge role 并让商品改变前一动作走向", appliesTo: ["product", "script"] },
  { id: "FAIL_STYLE_ONLY_CULTURE", warning: "文化只成为风格滤镜，没有动作逻辑", repairHint: "把 motif 的 motion/audio/productBridge 写入动作链", appliesTo: ["culture"] },
  { id: "FAIL_UNFILMABLE_PROOF", warning: "证明方式不可见或过度依赖字幕", repairHint: "换成 closeup/process/comparison proof", appliesTo: ["proof", "shot"] },
]
